server:
  port: 9191

spring:
  application:
    name: gateway
      
zuul:
  routes:
    adder:
      path: /add/**
      stripPrefix: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7171/eureka/    
        